# Generated by Django 4.2.17 on 2026-01-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0002_historicalworkplace_historicalcoworking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coworkingimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workplaceimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='coworkingimage',
            name='url',
        ),
        migrations.RemoveField(
            model_name='workplaceimage',
            name='url',
        ),
        migrations.AddField(
            model_name='coworkingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coworkings/'),
        ),
        migrations.AddField(
            model_name='workplaceimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workplaces/'),
        ),
        migrations.AlterField(
            model_name='coworkingimage',
            name='coworking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coworking.coworking'),
        ),
        migrations.AlterField(
            model_name='coworkingimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workplaceimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workplaceimage',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coworking.workplace'),
        ),
    ]
